<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MacBook-Pro-de-Juan.local" name="testLibrary.SmokeTestRemoteProd" tests="6" failures="1" timestamp="22 Jun 2016 22:25:22 GMT" time="11.878" errors="0">
  <testcase name="fillAccountForm" time="2.462" classname="testLibrary.SmokeTestRemoteProd"/>
  <testcase name="applyPromoCode" time="1.966" classname="testLibrary.SmokeTestRemoteProd"/>
  <testcase name="verifyProductPrice" time="0.562" classname="testLibrary.SmokeTestRemoteProd">
    <failure type="java.lang.AssertionError" message="Price is the same expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: Price is the same expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertFalse(Assert.java:63)
	at testLibrary.SmokeTestRemoteProd.verifyProductPrice(SmokeTestRemoteProd.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- verifyProductPrice -->
  <testcase name="fillBillingForm" time="1.771" classname="testLibrary.SmokeTestRemoteProd"/>
  <testcase name="fillPaymentForm" time="1.001" classname="testLibrary.SmokeTestRemoteProd"/>
  <testcase name="fillShippingForm" time="4.116" classname="testLibrary.SmokeTestRemoteProd"/>
</testsuite> <!-- testLibrary.SmokeTestRemoteProd -->
